# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a0509f65d766dad389cf99c0839534d58cc947ae9056b5df4e6df69b9f3cdf797e130d1c1399738eebf410a1f7d7dfc021d0ea3804a34b24673d4f0384da6803

test:
  secret_key_base: 76744cbbe518a4e92f24485eb7f90f2185c0035c69b75dfed64b0b54a1971e9a0b94b256f7b5e1c40a82a2a9d483bd32358d1e5c411e2831959dde2ef12f2944

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
